---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-mock-module
    kind: solution
    catalog_id: a6e50733-8b10-4ec6-a847-8f4058c27889
    offering_id: a91c3d21-5350-48ae-a0b6-a81666d44d3e
    variations:
      - name: standard
        mark_ready: true
        destroy_resources_on_failure: true
        destroy_workspace_on_failure: false
        install_type: fullstack
        validation_type: schematics
        # scc:
        #   instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
        #   region: us-south
