---
- name: Example of JSON body parsing with uri module
  connection: local
  gather_facts: true
  hosts: localhost
  tasks:

    - name: Example of JSON body parsing with uri module
      uri: 
        url: https://jsonplaceholder.typicode.com/users
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: data
      # failed_when: <optional condition based on JSON returned content>

    - name: Set Statefile
      set_fact:
        statefile: "{{ data.json | to_json }}"

    - name: Check for old version of landing zone
      ansible.builtin.shell: |
            ADDRESS_LIST=$(echo '{{ statefile }}' | jq -r '.[] | select(.name == "Leanne Graham") | .id')
            echo $ADDRESS_LIST